#!/bin/bash

WORKSPACE=$1

## move into desired workspace
echo package clone path: $WORKSPACE/src
cd ~/$WORKSPACE/src

## install required UR and robotiq packages cameras
##--------------------------------------------------------------##

## clone required git repos
git clone -b kinetic-devel https://github.com/ros-industrial/universal_robot.git
git clone -b kinetic-devel https://github.com/dniewinski/ur_modern_driver.git
git clone -b kinetic-devel https://github.com/ros-industrial/robotiq.git

## clone custom NERVE UR5e related packages (mount URDF, moveit config and ikfast solver)
git clone -b master https://github.com/flynn-nerve/ur5e_d435_millibar_combined_r2f85_moveit_config.git
git clone -b master https://github.com/flynn-nerve/ur5e_d435_millibar_combined_r2f85_ikfast_manipulator_plugin.git
git clone -b master https://github.com/flynn-nerve/d435_millibar_r85_mount_structure.git

## install realsense cameras
##--------------------------------------------------------------##

## clone librealsense package
git clone -b master https://github.com/IntelRealSense/librealsense.git

## install necessary libraries
sudo apt-get install git libssl-dev libusb-1.0-0-dev pkg-config libgtk-3-dev libglfw3-dev -y

## add keyserver to list of repositories
sudo apt-key adv --keyserver keys.gnupg.net --recv-key C8B3A55A6F3EFCDE || sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-key C8B3A55A6F3EFCDE
sudo add-apt-repository "deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial main" -u

## install additional libraries
sudo apt-get install librealsense2-dkms librealsense2-utils librealsense2-dev librealsense2-dbg -y

## update and upgrade
sudo apt-get update && sudo apt-get upgrade

## check for and install missing dependencies and build workspace
rosdep install --from-paths src --ignore-src --rosdistro kinetic -y
cd ..
catkin build
source ./devel/setup.bash

## run realsense camera scripts to add cameras to udev rules and patch software
## your cameras WILL NOT WORK without allowing this step to happen
cd src/librealsense
./scripts/setup_udev_rules.sh
./scripts/patch-realsense-ubuntu-lts.sh
cd ..

## clone realsense package (not realsense-ros package)
## clone ddynamic_reconfigure package into realsense package
git clone -b development https://github.com/doronhi/realsense.git
cd realsense
git clone -b kinetic-devel https://github.com/pal-robotics/ddynamic_reconfigure.git
cd ..

## install rgbd_launch package for realsense cameras
sudo apt-get install ros-kinetic-rgbd-launch

## return to base directory
cd ..

## check for and install missing dependencies again, build
rosdep install --from-paths src --ignore-src --rosdistro kinetic -y
catkin build
source ./devel/setup.bash

## install moveit! packages
##--------------------------------------------------------------##
rosdep update
sudo apt-get update
sudo apt-get dist-upgrade

## install moveit!
sudo apt install ros-kinetic-moveit

## cd to src folder and clone tutorial and panda_moveit_config package for testing/practice/reference
cd src
git clone -b kinetic-devel https://github.com/ros-planning/moveit_tutorials.git
git clone -b kinetic-devel https://github.com/ros-planning/panda_moveit_config.git

## return to base directory
cd ..

## install dependencies, build and source workspace
rosdep install --from-paths src --ignore-src --rosdistro kinetic -y
catkin build
source ./devel/setup.bash
